### ISSUE TITLE
Add install ZSH

### ISSUE THREAD

**Issue by galihap** [aqidd/mac-env-script#1]
https://github.com/robbyrussell/oh-my-zsh

would be a great addition

**Comment by aqidd** [comment]
not really an oh-my-zsh user, but perhaps it would be useful in the future, 

adding options to add extra command line arguments parameter ( `oh-my-zsh` is supported )

closed in https://github.com/aqidd/mac-env-script/commit/260db425c30bb7ae73f20d11c8b6696f18724d9a
